import{S as b,i as h,a as $}from"./assets/vendor-Rdv7LHNr.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function r(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(s){if(s.ep)return;s.ep=!0;const o=r(s);fetch(s.href,o)}})();const S=new b(".gallery a",{captionsData:"alt",captionDelay:250}),w=document.querySelector(".gallery");function x(e){w.insertAdjacentHTML("beforeend",R(e)),S.refresh()}function R(e){return e.hits.map(({webformatURL:t,largeImageURL:r,tags:l,likes:s,views:o,comments:c,downloads:L})=>`<li class="gallery-item">
					<a class="gallery-link" href="${r}">
						<figure class="gallery-figure ">
							<img class="gallery-image" src="${t}" alt="${l}" loading="lazy">
									<ul class="img-wrap">
									<li>Likes<span>${s}</span></li>
									<li>Views<span>${o}</span></li>
									<li>Comments<span>${c}</span></li>
									<li>Downloads<span>${L}</span></li>
								</ul>
						</figure>
					</a>
				</li>
		`).join("")}function q(){w.insertAdjacentHTML("afterEnd",`<div class='loader-wrapper'>
    <span class="loader">Loading</span>
    </div>`)}const n={info:"Please enter a value in the search field!",endOfSearch:"We're sorry, but you've reached the end of search results.",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there are no connection to the server. Please try again later!",exception:"Exception: We have some issue with connection. Please try again later!"},a={green:"#14b454",yellow:"#e52a2a",red:"#e5c32a"},f={click:"click",submit:"submit"};function i(e,t){h.info({position:"topRight",backgroundColor:`${t}`,message:`${e}`})}const O="46849284-22f4e981648a1afff2e3fd4a3",P="https://pixabay.com/api/?",g={params:{key:O,image_type:"photo",orientations:"horizontal",safesearch:!0,page:1,per_page:15}};async function E(e,t){try{return q(),g.params.page=t,g.params.q=e,(await $.get(P,g)).data}catch(r){if(r.response){const{data:l}=r.response;i(`${n.exception} ERROR: ${l}`,a.yellow)}else r.request?i(`${n.exception} ERROR: ${r.request}`,a.yellow):i(`${n.exception} ERROR: ${r.message}`,a.yellow)}}let d="",u="",m=1;const M=15,p=document.querySelector(".gallery"),H=document.querySelector(".search-form"),y=document.querySelector(".load-more-btn");H.addEventListener("submit",T);y.addEventListener("click",async()=>{try{d=f.click,await v(u,m);const e=document.querySelector("li"),{height:t}=e.getBoundingClientRect();A(t*2,0)}catch(e){i(n.exception+e.messages,a.yellow)}});async function T(e){try{e.preventDefault();const t=e.target,r=t.elements.search.value.trim();if(d=f.submit,y.classList.remove("visible"),h.destroy(),(u!==r||d===f.submit)&&(p.innerHTML="",u=t.elements.search.value.trim(),m=1),!r){i(n.info,a.green),p.innerHTML="";return}await v(u,m),t.reset()}catch(t){i(n.exception+t.messages,a.yellow)}}async function v(e,t){try{e===u&&d===f.click&&(m+=1,t+=1);const r=await E(e,t);if(B(),G(r)){const l=Math.round(r.totalHits/t);x(r),I(l)}}catch(r){i(n.exception+r.messages,a.yellow)}}function A(e=0,t=0){window.scrollBy({top:e,left:t,behavior:"smooth"})}function B(){document.querySelector(".loader-wrapper").remove()}function G(e){return e?e&&e.totalHits===0?(i(n.warning,a.red),p.innerHTML="",!1):!0:(p.innerHTML="",!1)}function I(e){if(e<=M){y.classList.remove("visible"),i(n.endOfSearch,a.green);return}y.classList.add("visible")}
//# sourceMappingURL=index.js.map
